
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += $(wildcard src/*.cpp)

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ${PICOLIBSDK_PATH}

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
