[platformio]
default_envs = esp32_arduino

[env:esp32_arduino]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32s3
lib_deps =
    ../../../core
    ../common

build_unflags =
    -std=gnu++11
    -std=gnu++0x
    -Os
    -fno-jump-tables
    -fno-tree-switch-conversion

build_flags =
    -std=gnu++17
    -O2
    -fjump-tables
    -ftree-switch-conversion
    -I../common/src/fatfs

build_src_filter =
    +<*>
    +<fatfs/*.c>
