[platformio]
default_envs = esp32_arduino

[env:esp32_arduino]
framework = arduino
platform = espressif32
board = seeed_xiao_esp32s3
lib_deps = https://github.com/hideakitai/PCA95x5
build_unflags =
    -std=gnu++11
    -std=gnu++0x
build_flags =
    -std=gnu++17
    -DBOARD_HAS_PSRAM=0
    -O2
    -I../../../core/include/
    -I../../fatfs/source/
    -I../common/include/

#    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE

build_src_filter =
    +<*>
    +<../../common/src/*>
    +<../../../fatfs/source/ff.c>
    +<../../../fatfs/source/ff_system.c>
    +<../../../fatfs/source/ff_unicode.c>
    +<../../../../core/src/*>
